### PR TITLE
Add Dynamic, which proudly uses WC as well!

### PR DESCRIPTION
**Pull request by turbahn**
Adding Dynamic, which offers a free multi-chain wallet adapter and also proudly leverages WC (and WC v2!!)

### CODE REVIEW

**Comment by turbahn** [comment]
Also - congrats on putting this list together. Super cool

**Comment by crypblizz8** [comment]
Amazing, thanks for all you do at Dynamic!

**Comment by Buyzed** [comment]
f38bcf48936cfdc5fa728310e502f0456e48dd62

**Comment by Buyzed** [comment]
e4664fae97acf1e903395580a10ccc3408aa3cd2

**Pull request merged**
